baseURL = 'https://github.com/merisssas/Bot'
title = 'Teleload'
disablePathToLower = true
enableGitInfo = true
defaultContentLanguage = 'en'


[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookTheme = 'auto'
BookToC = true
BookLogo = 'logo.png'
BookSection = '*'
BookRepo = 'https://github.com/krau/Teleload'
BookCommitPath = 'commit'
BookEditPath = 'edit/main/docs'
BookDateFormat = '2006/01/02'
BookSearch = false

[languages]

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 1

[[languages.en.menu.before]]
name = "ðŸ”— GitHub"
url = "https://github.com/merisssas/Bot"
weight = 10

[markup]
[markup.goldmark.renderer]
unsafe = true
